name: Kanola Plasma Desktop
id: kanola-plasma
vibversion: 1.0.2

stages:
- id: build
  base: ghcr.io/kanola-images/base:main
  addincludes: true
  labels:
    maintainer: Kanola Contributors
  args:
    DEBIAN_FRONTEND: noninteractive
  runs:
    commands:
      - echo 'APT::Install-Recommends "1";' > /etc/apt/apt.conf.d/01norecommends

  modules:
  - name: init-setup
    type: shell
    commands:
    - lpkg --unlock
    - apt update

  - name: vanilla-tools
    type: shell
    sources:
      - type: tar
        url: https://github.com/Vanilla-OS/vanilla-tools/releases/download/continuous/vanilla-tools.tar.gz
    commands:
      - mkdir -p /usr/bin
      - cp /sources/vanilla-tools/vanilla-tools/vanilla-tools/lpkg /usr/bin/lpkg
      - cp /sources/vanilla-tools/vanilla-tools/vanilla-tools/cur-gpu /usr/bin/cur-gpu
      - cp /sources/vanilla-tools/vanilla-tools/vanilla-tools/prime-switch /usr/bin/prime-switch
      - chmod +x /usr/bin/lpkg
      - chmod +x /usr/bin/cur-gpu
      - chmod +x /usr/bin/prime-switch

  - name: packages-modules
    type: includes
    includes:
      - modules/10-display-manager.yml
      - modules/20-plasma-core.yml
      - modules/30-plasma-essentials.yml
      - modules/161-plasma-utilities.yml
      - modules/200-plasma-common.yml
      - modules/999-cleanup.yml

  - name: nvidia-official-repo
    type: shell
    commands:
    - curl -fSsL https://developer.download.nvidia.com/compute/cuda/repos/debian12/x86_64/3bf863cc.pub | gpg --dearmor -o /usr/share/keyrings/nvidia-drivers.gpg
    - echo 'deb [signed-by=/usr/share/keyrings/nvidia-drivers.gpg] https://developer.download.nvidia.com/compute/cuda/repos/debian12/x86_64/ /' > /etc/apt/sources.list.d/nvidia-drivers.list
    - apt update

  - name: nvidia-official-driver
    type: shell
    commands:
    - apt-mark hold nvidia-kernel-open nvidia-driver nvidia-vaapi-driver nvidia-settings nvidia-persistenced nvidia-smi libnvidia-cfg1 libnvidia-glcore libnvidia-glvkspirv libnvidia-gpucomp libnvidia-fbc1 nvidia-container-toolkit
    modules:
      - name: install-nvidia
        type: apt
        sources:
          - packages:
            - nvidia-kernel-open
            - nvidia-driver
            - nvidia-vaapi-driver
            - nvidia-settings
            - nvidia-persistenced
            - cuda-drivers
            - libnvidia-cfg1
            - libnvidia-glcore
            - libnvidia-glvkspirv
            - libnvidia-gpucomp
            - libnvidia-fbc1
            - nvidia-container-toolkit

  - name: nvidia-sysd-units
    type: shell
    commands:
    - mkdir -p /etc/systemd/system/systemd-suspend.service.wants
    - mkdir -p /etc/systemd/system/systemd-hibernate.service.wants
    - ln -s /usr/lib/systemd/system/nvidia-suspend.service /etc/systemd/system/systemd-suspend.service.wants/nvidia-suspend.service
    - ln -s /usr/lib/systemd/system/nvidia-hibernate.service /etc/systemd/system/systemd-hibernate.service.wants/nvidia-hibernate.service
    - ln -s /usr/lib/systemd/system/nvidia-resume.service /etc/systemd/system/systemd-hibernate.service.wants/nvidia-resume.service

  - name: extra-utilities
    type: apt
    sources:
      - packages:
        - switcheroo-control

  - name: enable-wayland
    type: shell
    commands:
    - mkdir -p /etc/udev/rules.d
    - ln -s /dev/null /etc/udev/rules.d/61-gdm.rules

  - name: cleanup
    type: shell
    commands:
    - apt autoremove -y
    - apt clean
    - apt remove -y zutty gnome-shell-extension-prefs
    - SUDO_FORCE_REMOVE=yes apt purge -y sudo
    - lpkg --lock
    - rm /etc/apt/sources.list.d/nvidia-drivers.list

  - name: sysconf-setup
    type: shell
    commands:
      - rsync -a /etc/ /sysconf/

  - name: fsguard
    type: fsguard
    CustomFsGuard: false
    FsGuardLocation: "/usr/sbin/FsGuard"
    GenerateKey: true
    FilelistPaths: ["/usr/bin"]
    modules:
      - name: remove-prev-fsguard
        type: shell
        commands:
          - rm -rf /FsGuard
          - rm -f ./minisign.pub ./minisign.key
          - chmod +x /usr/share/init.d/010-fsguard.sh

  - name: cleanup2
    type: shell
    commands:
      - rm -rf /tmp/*
      - rm -rf /var/tmp/*
      - rm -rf /sources
